thresholds:
  low: 1050.0 # 触发买入提醒的低价阈值 (元/克)
  high: 1190.0 # 触发卖出提醒的高价阈值 (元/克)

fixed_investment:
  enabled: true
  day_of_week: [0,1,2,3,4] # 每周一定投 (0=Mon, 6=Sun)

dip_buy:
  enabled: false
  threshold: 0.05
  reference_price: 1100

notifiers:
  discord:
    enabled: true
    webhook_url: ""
  feishu:
    enabled: true
    webhook_url: ""
  telegram:
    enabled: false
    token: ""
    chat_id: ""
  wecom:
    enabled: false
    webhook_url: "" # 企业微信机器人webhook地址
  pushplus:
    enabled: false
    token: "" # pushplus token
  serverchan:
    enabled: true
    send_key: "" # Server酱 send_key
